    /*============================================================
	Script Name  : 1.Database Creation.sql
    Purpose      : Creates the Swiggy_Data database
    Description  : This script creates the database that will be 
                   used to store Swiggy restaurant data for analysis
    Created On   : 28-Oct-2025
    Created By   : Chaitanya Pangidi
	==============================================================*/

CREATE DATABASE SWIGGY_DATA